module.exports = [
  'Siemens AG',
  'Honeywell International',
  'Bosch Global',
  'Johnson Controls',
  'Schneider Electric',
  'Pfizer Inc.',
  'Walmart Inc.',
  'Chevron Corporation',
  'General Electric (GE)',
  'Nest Labs',
  'Caterpillar Inc.',
  'Emerson Electric',
  'AbbVie Inc.',
  'Target Corporation',
  'Enel Green Power',
  'Tesla Energy',
  'Phillips Healthcare',
  'Medtronic plc',
  'John Deere & Co.',
  'Ford Motor Company (Industrial)',
  'Lockheed Martin',
  'Northrop Grumman',
  'ExxonMobil',
  'Shell Energy',
  'BASF SE',
  'Bayer AG',
  'Novartis AG',
  'Kroger Co.',
  'Home Depot',
  'FedEx Logistics'
];
